### PR TITLE
feat: ESM only

### PR DESCRIPTION
**Pull request by stefan-guggisberg**
BREAKING: Removed CommonJS support. This package is native ESM from now on.

### CODE REVIEW

**Comment by colinbendell** [comment]
What was the problem that dropping CSJ support was the solution? This feels like this just create a lot of downstream toil for no net value for either dependencies nor this project.

**Comment by stefan-guggisberg** [comment]
Dependencies moved to ESM only.

**Comment by colinbendell** [comment]
But what was the problem being solved? There are over 150 downstream open source projects using the commonjs form that you have orphaned from security updates. These projects now need to refactor and adopt ESM because of this decision. 

So my question is what problem does this PR actually solve?

**Comment by stefan-guggisberg** [comment]
> There are over 150 downstream open source projects using the commonjs form that you have orphaned from security updates. These projects now need to refactor and adopt ESM because of this decision.

Security updates are still made on the 3.x branch.

**Comment by stefan-guggisberg** [comment]
> So my question is what problem does this PR actually solve?

That we're not stuck on outdated dependencies.

**Comment by tripodsan** [comment]
> There are over 150 downstream open source projects using the commonjs form that you have orphaned from security updates.

many of the projects switch to ESM only: semantic-release https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0, the entire unified ecosystem https://github.com/unifiedjs/unified/releases/tag/10.0.0 and many more.

**Comment by colinbendell** [comment]
Sure, a few other tools are going ESM only. That doesn't mean that this is good for the ecosystem. By going ESM only you create downstream toil that adds no value. It's just wasted work.

**Pull request merged**
